Added the first draft of README.md
Codher/elm-workshop pull request #1
Opened 2017-09-25 22:21 UTC by halfzebra

2017-09-27 16:38 UTC, raulpineda requested changes

2017-09-27 16:38 UTC, raulpineda commented on README.md
> +Have you ever tried programming in a language, where compiler is your best friend? Imagine an app without errors at run-time.
where the compiler

2017-09-27 16:38 UTC, raulpineda commented on README.md
> +Immutabile, Pure and Reactive by nature all that awailable now!
Maybe mention why are immutable, pure and reactive good to have characteristics. Like "pure functions by nature, so you don't have to worry about ugly and unexpected side effects"

2017-09-27 16:38 UTC, raulpineda commented on README.md
> +Immutabile, Pure and Reactive by nature all that awailable now!
available

2017-09-27 16:38 UTC, raulpineda commented on README.md
> +Get an introduction to Elm Compiler and Time-Travelling Debugger and start coding!
In this workshop you'll get an introduction to the Elm Compiler (so you can build your first application or something), and the Time-Travelling debugger (so you...) and start coding in Elm!

2017-09-27 16:38 UTC, raulpineda commented on README.md
> +You can use whichever code editor you prefer.
Maybe add suggestions? A link to atom or vs code or whatever

2017-09-27 16:38 UTC, raulpineda commented on README.md
> +Functional Programming is fun and easy if you learn by doing.
Maybe start with the benefits of functional programming (the immutable, pure and reactive paragraph) and then say it's easy and fun

2017-09-27 16:38 UTC, raulpineda commented on README.md
> +## Agenda
The agenda should go after the introduction

2017-09-27 17:49 UTC, jycr753 commented on README.md
> +Have you ever tried programming in a language, where compiler is your best friend? Imagine an app without errors at run-time.
Where the compiler

2017-09-27 17:49 UTC, jycr753 commented on README.md
> +Immutabile, Pure and Reactive by nature all that awailable now!
Immutable

2017-10-01 18:44 UTC, halfzebra commented
@raulpineda @jycr753 Thanks for the review! I have fixed the typos and included more info.

2017-10-02 20:22 UTC, raulpineda approved these changes

2017-10-02 20:23 UTC, raulpineda commented
Looks great! Let me know if it's still a WIP, otherwise I'll merge :)

2017-10-02 22:06 UTC, halfzebra commented
@raulpineda Thanks!

I think that's pretty much it for the description, I'll start working on examples and exercises.

Feel free to merge this PR! :slightly_smiling_face:

2017-10-03 06:14 UTC, merged